Add initial bruno tests
aspirepress/AspireCloud pull request #96
Opened 2024-11-06 05:46 UTC by eadamsatx

# Pull Request

## What changed?

Added some initial bruno tests for plugins endpoints

## Why did it change?

No bruno tests existed for these endpoints

## Did you fix any specific issues?

No

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

2024-11-06 14:16 UTC, chuckadams requested changes

2024-11-06 14:16 UTC, chuckadams commented on bruno/Plugins/Plugin Info.bru
> +  API_URL: api.wordpress.org
This should be removed from the test, since it's already set in the environment that one selects from the dropdown in the upper right.  For testing against api.wordpress.org for example, you would select "WordPressDotOrg Update API" from the list.

<img width="631" alt="image" src="https://github.com/user-attachments/assets/1d08d034-793a-4fda-b797-c8f6d65fdf8a">

2024-11-06 14:16 UTC, chuckadams commented on bruno/Plugins/Plugins Info.bru
> +  API_URL: wordpress.org
Remove this here as well.  Everything else looks good to me.

2024-11-06 23:02 UTC, asirota approved these changes

2024-11-07 00:39 UTC, chuckadams approved these changes

2024-11-07 00:39 UTC, merged